config/routes.rb
Rails.application.routes.draw do
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'finder#index'

  get '/alphabetized' => 'finder#alphabetized'

  get '/missing_email' => 'finder#missing_email'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :fullname, :phonenumber, presence: true
end

app/models/province.rb
class Province < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:fullname, :phonenumber, :email, :image, :notes)
    end
end

app/controllers/finder_controller.rb
class FinderController < ApplicationController
before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.all.order(:fullname)
  end

  def missing_email
    @customers = Customer.all.where(email: "")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/finder_helper.rb
module FinderHelper
end

app/views/customers/_customer.html.erb
<div class="customer">
 <h2><%= customer.fullname %></h2>
  <h1><%= customer.notes %></h1>
 <p><%= image_tag customer.image %></p>
 <p><%= customer.phonenumber %></p>
 <p>Email: <%= customer.email %></p>
 <p>
   <%= link_to 'Show', customer %> -
   <%= link_to 'Edit', edit_customer_path(customer) %> -
   <%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %>
 </p>
</div>

app/views/customers/_form.html.erb
<%= form_for(customer) do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fullname %>
    <%= f.text_field :fullname %>
  </div>

  <div class="field">
    <%= f.label :phonenumber %>
    <%= f.text_field :phonenumber %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Fullname</th>
      <th>Phonenumber</th>
      <th>Email</th>
      <th>Image</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.fullname %></td>
        <td><%= customer.phonenumber %></td>
        <td><%= customer.email %></td>
        <td><%= customer.image %></td>
        <td><%= customer.notes %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fullname:</strong>
  <%= @customer.fullname %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @customer.phonenumber %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Image:</strong>
  <%= @customer.image %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @customer.notes %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/finder/alphabetized.html.erb
<p id="notice"><%= notice %></p>

<h2>Alphabetized Customers</h2>

<%= link_to 'New Customer', new_customer_path %>
<%= link_to 'missing_email', missing_email_path %>

    <% @customers.each do |customer| %>
    <%= render customer %>
    <%end%>

app/views/finder/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Customers</h2>

<%= link_to 'New Customer', new_customer_path %>
<%= link_to 'missing_email', missing_email_path %>
<%= link_to 'alphabetized', alphabetized_path %>

    <% @customers.each do |customer| %>
    <%= render customer %>
    <%end%>

app/views/finder/missing_email.html.erb
<p id="notice"><%= notice %></p>

<h2>Customers Missing Email Addresses</h2>

<%= link_to 'New Customer', new_customer_path %>
<%= link_to 'alphabetized', alphabetized_path %>

    <% @customers.each do |customer| %>
    <%= render customer %>
    <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRMChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>